#!/usr/bin/env perl

use strict;
use warnings;

use File::ShareDir qw/module_dir/;
use Path::Tiny;
use File::Copy::Recursive qw/dircopy/;
use App::EvalServerAdvanced::Sandbox;

my $skel_dir = path(module_dir("App::EvalServerAdvanced::Sandbox"))->realpath;
my $sandbox_dir = path("./sandbox")->realpath;

$sandbox_dir->mkpath;

dircopy($skel_dir, $sandbox_dir);